// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vctxmcojstcvxlxuklxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdHhtY29qc3RjdnhseHVrbHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzQzMDgsImV4cCI6MjA1OTcxMDMwOH0._46EBeATWSrDXKHKFvLBK0fJPDCfTordf2x4EHpUafY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);